Add productsCount attribute to SmartCollections
bold-commerce/bold-shopify-toolkit pull request #127
Opened 2020-12-07 21:18 UTC by lizkenyon

* This attribute list the number of products in a smartCollection
* Shopify Docs https://shopify.dev/docs/admin-api/rest/reference/products/smartcollection?api%5Bversion%5D=2020-01#show-2020-01

2020-12-14 21:43 UTC, dgetson approved these changes
Looks good to me

2020-12-15 17:18 UTC, Wryte requested changes

2020-12-15 17:18 UTC, Wryte commented on src/Models/SmartCollection.php
> +     * @return int
Should this have `|null` as well?

2020-12-15 17:39 UTC, lizkenyon commented on src/Models/SmartCollection.php
> +     * @return int
Added!

2020-12-15 19:25 UTC, Wryte approved these changes

2020-12-15 19:27 UTC, merged