Remove valueType from metafield
bold-commerce/bold-shopify-toolkit pull request #147
Opened 2022-03-29 20:13 UTC by jim-boldcommerce

I'm still getting errors from the shopify API from the valueType field. Seems like shopify is removing it entirely. Last merge marked it as deprecated, but this one would definitely be a breaking change

Breaking Change Guide

1. `BoldApps\ShopifyToolkit\Models\Metafield::valueType` has been
   removed and should be replaced with `BoldApps\ShopifyToolkit\Models\Metafield::type`

2. `BoldApps\ShopifyToolkit\Models\Metafield::getValueType` and `BoldApps\ShopifyToolkit\Models\Metafield::setValueType` have been removed
    and should be replaced with `BoldApps\ShopifyToolkit\Models\Metafield::getType` and `BoldApps\ShopifyToolkit\Models\Metafield::setType`

3. The type field has new types than ones that existed in valueTypes, you will need to update to a supported one from the list on this page : https://shopify.dev/apps/metafields/types#metafield-value_type-deprecation

2022-03-29 21:15 UTC, Wryte requested changes
Definitely worried about this one being a breaking change. Is there a way we can only serialize `valueType` in if it's set?

2022-03-29 21:20 UTC, jim-boldcommerce commented
Do we do specific serialization logic anywhere else? Currently this gets used as a list on a product, and then the whole product is serialized

2022-03-31 15:04 UTC, Wryte approved these changes

2022-03-31 15:04 UTC, merged

2022-03-31 15:09 UTC, digiexchris commented
This needs to be rewritten in Rust.

2022-03-31 15:14 UTC, jim-boldcommerce commented
> This needs to be rewritten in Rust.

https://www.youtube.com/watch?v=NUkibfzeQ7g