Trigger `afterRequest()` from `requestHookInterface` after every call
bold-commerce/bold-shopify-toolkit pull request #155
Opened 2023-03-24 21:17 UTC by deepsidhu1313

* This will trigger `afterRequest()` function from `ShopifyApiHandler` if implemented. Which then can be used to slow down api call to avoid limit exhaustion, or to notify warnings in case deprecated reason is being returned in response headers
* Also added composer.lock to gitignore as this a library
* fixed unit test

2023-03-24 22:12 UTC, Wryte requested changes

2023-03-24 22:12 UTC, Wryte commented on src/Services/Client.php
> +        $this->requestHookInterface->afterRequest($response);
Not sure how this is different since `finally`s always triggers already? If anything it would trigger less since the catch isn't catching `Throwable`s

https://www.php.net/manual/en/language.exceptions.php#language.exceptions.finally

2023-03-24 22:12 UTC, Wryte commented on src/Support/ShopifyApiHandler.php
> +        if (!empty($response) && is_a($response, Response::class)) {
I don't like the idea of leaving these empty if blocks in the code. If we want to guide people how to use this method then we should add it to the README.

2023-03-25 00:58 UTC, deepsidhu1313 commented on src/Support/ShopifyApiHandler.php
> +        if (!empty($response) && is_a($response, Response::class)) {
make sense, i will revert this change and add to readme.

2023-04-17 19:16 UTC, deepsidhu1313 commented on src/Support/ShopifyApiHandler.php
> +        if (!empty($response) && is_a($response, Response::class)) {
moved code to readme as example

2023-04-17 19:16 UTC, deepsidhu1313 commented on src/Services/Client.php
> +        $this->requestHookInterface->afterRequest($response);
reverted change

2023-04-17 19:25 UTC, Wryte commented on README.md
> +## Advance Usage of ShopifyApihandler
Let's move this section to below examples

2023-04-18 18:41 UTC, Wryte commented on README.md
> +### Advance Usage of ShopifyApihandler
Let's remove this for now until we have a fuller explanation of what to do with subclassing or implementing your own `ShopifyApihandler`.

2023-05-02 14:38 UTC, deepsidhu1313 commented on README.md
> +### Advance Usage of ShopifyApihandler
Done

2023-06-05 20:10 UTC, merged